---
- name: build node state
  hosts: build
  become: yes

  tasks:
  - name: check git package
    apt:
      name: git
      state: present
  
  - name: check jdk package
    apt:
      name: default-jdk
      state: present

  - name: check maven package
    apt:
      name: maven
      state: present

  - name: check docker package
    apt:
      name: docker.io
      state: present   

  - name: copy dockerhub secrets (kostyl)
    copy:
      src: ~/scrts_prjct/dr_pass.txt
      dest: /tmp/vkr_project


- name: prod node state
  hosts: prod
  become: yes

  tasks:
  - name: check docker package
    apt:
      name: docker.io
      state: present
