---
- name: make atrifact and push to registry
  hosts: build
  become: yes

  tasks:
  - name: create temp directory
    ansible.builtin.file:
      path: /tmp/vkr_project
      state: directory

  - name: clone project repo
    git:
      repo: https://github.com/elmcslay/DO_edu-VKR-prjct.git
      dest: /tmp/vkr_project
      clone: yes

  - name: check artifact is exists
    stat:
      path: /tmp/vkr_project/target/hello-1.0.war
    register: result

  - name: create artifact, if it does not exist
    shell: mvn package
    args:
      chdir: /tmp/vkr_project
    when: not result.stat.exists 

  - name: create docker image
    shell: docker build -t vkr-img target/
    args:
      chdir: /tmp/vkr_project

  - name: login on docker registry
    shell: cat dr_pass.txt | docker login --username elmcslay --password-stdin
    args:
      chdir: /tmp/vkr_project

  - name: tag docker image
    shell: docker tag vkr-img elmcslay/vkr-img:1.0

  - name: push image to registry
    shell: docker push elmcslay/vkr-img:1.0  


- name: pull artifacts from registry
  hosts: prod
  become: yes

  tasks:
  - name: pull & run
    shell: docker run -d -p 8080:8080 elmcslay/vkr-img:1.0